stages:
  - format
  - lint
  - plan
  - apply
  - destroy
  - publish

variables:
  AWS_ROLE_NAME: gitlab_runner
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID_SANDPIT
  AWS_PROFILE_NAME: cmdlab-sandpit
  AWS_ACCOUNT_ID_AGGREGATOR: $AWS_ACCOUNT_ID_AGGREGATOR
  
format:
  stage: format
  tags:
    - cmd
  script:
    - make formatCheck

lint:
  stage: lint
  tags:
    - cmd
  script:
    - make lint

plan:
  stage: plan
  tags:
    - cmd

  script:
    - make plan

apply:
  stage: apply
  tags:
    - cmd
  script:
    - make apply

destroy:
  stage: destroy
  tags:
    - cmd
  script:
    - make destroy

publish:
  stage: publish
  tags:
    - cmd
  script:
    - make publish
  variables:
    GIT_STRATEGY: clone
  only:
    - master
    - tags